apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 580183190051.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 580183190051.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 382a8ba0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
